### ISSUE TITLE
David Elzinga MiniProject1 Idea

### ISSUE THREAD

**Issue by David-Elzinga** [leighpearcy/MiniProject1#1]
Hi Leigh,

Here is my project idea for MiniProject1. Below are the set of instructions we are tasked with. 

1. Compare word frequencies between two works of a single author.
2. Compare word frequencies between works of two authors.
3. Are there some words preferred by one author but used less frequently by another author?

- For problem number 1, I plan on comparing word frequencies between two scripts of the TV show, "The Office" 
- For problem number 2, I plan on comparing word frequencies between one script of the TV show, "The Office", and one script from the Netflix show, "Kim's Convivence"
- For problem number 3 I plan on using a statistical test to compare discrete distributions on the most common unique words from each show. That means I'll need to be careful of the problem of multiple comparisons so I plan on using a Holm correction.

Scripts for both shows should be available online, but I'll have to be careful to remove words that are actions (usually denoted in brackets) and character names (e.g. Bob Vance: "Bob Vance, Vance Refrigeration" should only register 2 instances of the word "Vance" since the first one was indicating the speaking character).  

Let me know your thoughts!

**Comment by leighpearcy** [comment]
Sounds fun, and challenging! Good luck! You could simplify by just comparing written scripts as opposed to spoken words. That way, you do not need to remove action descriptions or character names.
